### ISSUE TITLE
newest selenium ==4.3.0 breaks the example?

### ISSUE THREAD

**Issue by HeinrichHaller** [joeyism/linkedin_scraper#127]
I think the * in the requirements for selenium breaks the example. It gets 4.3.0 installed that apparently does not have the attribute 'find element by id' anymore. 
Like described here:
https://stackoverflow.com/questions/72754651/attributeerror-webdriver-object-has-no-attribute-find-element-by-xpath

selenium version after fresh install:
>>> selenium.__version__
'4.3.0'

error in the example:

>>> actions.login(driver, email, password) # if ema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moritz/.cache/pypoetry/virtualenvs/linkedin-TonP7aHi-py3.9/lib/python3.9/site-packages/linkedin_scraper/actions.py", line 26, in login
    email_elem = driver.find_element_by_id("username")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'

Has somebody a workaround? Thanks!

**Comment by matardy** [comment]
Yes, it breaks the examples. 
update requirements.txt file with this:
selenium==4.2.0
requests
lxml

**Comment by JBLarson** [comment]
Thank you @matardy
You're a life saver

**Comment by Sunishchal** [comment]
Is there a reason requirements.txt doesn't already have version types? Seems like that's an easy way to future proof this library. Happy to raise that PR if you think it's a good idea.
