### ISSUE TITLE
AttributeError: 'WebElement' object has no attribute 'find_element_by_class_name'

### ISSUE THREAD

**Issue by danielhangan** [joeyism/linkedin_scraper#136]
Traceback (most recent call last):
  File "/Users/hangandaniel/Documents/interlinked-se/data/scrapers/lkd.py", line 14, in <module>
    person = Person("https://www.linkedin.com/in/danielhangan", driver=driver)
  File "/Users/hangandaniel/Library/Python/3.9/lib/python/site-packages/linkedin_scraper/person.py", line 62, in __init__
    self.scrape(close_on_complete)
  File "/Users/hangandaniel/Library/Python/3.9/lib/python/site-packages/linkedin_scraper/person.py", line 87, in scrape
    self.scrape_logged_in(close_on_complete=close_on_complete)
  File "/Users/hangandaniel/Library/Python/3.9/lib/python/site-packages/linkedin_scraper/person.py", line 116, in scrape_logged_in
    self.name = root.find_element_by_class_name(selectors.NAME).text.strip()
AttributeError: 'WebElement' object has no attribute 'find_element_by_class_name'

My code:

```python
from selenium import webdriver
import chromedriver_binary
from linkedin_scraper import Person, actions

driver = webdriver.Chrome()


if __name__ == "__main__":
    email = "***"
    password = "***"
    actions.login(
        driver, email, password
    )  # if email and password isnt given, it'll prompt in terminal
    person = Person("https://www.linkedin.com/in/danielhangan", driver=driver)
```

**Comment by dmehrotra** [comment]
I'm having a similar issue. Any fixes?

**Comment by joeyism** [comment]
It may be a problem with login. Can you run
```python
from selenium import webdriver
import chromedriver_binary
from linkedin_scraper import Person, actions

driver = webdriver.Chrome()


if __name__ == "__main__":
    email = "***"
    password = "***"
    actions.login(
        driver, email, password
    )  # if email and password isnt given, it'll prompt in terminal
    print("Press enter after you've successfully logged in")
    person = Person("https://www.linkedin.com/in/danielhangan", driver=driver)
```
and ensure that you're fully logged in when the chrome driver opens?

**Comment by danielhangan** [comment]
@joeyism I can see how the scraper is logging in and going to the person page.
But it throws the error while loading the person's page, after it logged in.

Is there a **time.sleep** between load_page and  and find_element_by_class_name?

**Comment by abdou0102** [comment]
same problem
any solution plz

**Comment by joeyism** [comment]
> @joeyism I can see how the scraper is logging in and going to the person page. But it throws the error while loading the person's page, after it logged in.
> 
> Is there a **time.sleep** between load_page and and find_element_by_class_name?

Yea, it should wait until the top card is loaded.

[See](https://github.com/joeyism/linkedin_scraper/blob/master/linkedin_scraper/person.py#L107)

**Comment by jnzhnd** [comment]
This is probably an issue with selenium - see [this stackoverflow thread](https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el). Until this is fixed, you can solve it by downgrading selenium.

**Comment by joeyism** [comment]
For references, I have 
```
selenium==3.141.0
```
and on chrome side
```
'browserVersion': '107.0.5304.110'
'chromedriverVersion': '107.0.5304.18
```
You can check your drivers and stuff by running
```python
from selenium import webdriver
driver = webdriver.Chrome()
print(driver.capabilities)
```

**Comment by RogeMetz** [comment]
I'm facing the same error here:

Exception has occurred: AttributeError
'WebElement' object has no attribute 'find_element_by_class_name'
  File "C:\Users\rogem\Desktop\Project 02\LinkedIn Web Scraper.py", line 8, in <module>
    person = Person("https://www.linkedin.com/in/rogemetz", driver=driver)
    
Any solution?

**Comment by danielhangan** [comment]
@RogeMetz just downgrade selenium version. It worked for me.

**Comment by Hrovatin** [comment]
Are there any plans on making this package run with never version of selenium? I think the change in retrieving elements has been there for a while.

**Comment by teddsords** [comment]
I had the same issue and by downgrading Selenium, it works fine.

**Comment by popekabu** [comment]
fixed mine by searching every word in the project having the keyword "find_element_by_class_name" with "find_element". It seems the former is no longer used, probably deprecated

**Comment by joeyism** [comment]
This should be fixed now
