### ISSUE TITLE
I started a new repo and got the following error

### ISSUE THREAD

**Issue by eleijonmarck** [joeyism/linkedin_scraper#157]
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_class_name'

**Comment by eleijonmarck** [comment]
https://stackoverflow.com/a/72773269/3767229

**Comment by lusifer021** [comment]
I quess you downloaded a previous version of the module try using 
`pip install linkedin-scraper==2.11.0`

**Comment by ternaus** [comment]
I get the same error with `linkedin-scraper==2.11.0`

**Comment by lusifer021** [comment]
Can you attach a screenshot of which function you are using?

**Comment by ternaus** [comment]
```
from linkedin_scraper import Person, actions
from selenium import webdriver
driver = webdriver.Chrome()

email = <EMAIL>
password = <PASSWORD>

actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5", driver=driver)

print(person.name)
```

=>

```
Traceback (most recent call last):
  File "/mnt/evo850/workspace/SalesBrain.tech/scripts/get_person.py", line 9, in <module>
    person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5", driver=driver)
  File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 63, in __init__
    self.scrape(close_on_complete)
  File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 88, in scrape
    self.scrape_logged_in(close_on_complete=close_on_complete)
  File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 261, in scrape_logged_in
    self.get_name_and_location()
  File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 235, in get_name_and_location
    top_panels = self.driver.find_elements_by_class_name("pv-text-details__left-panel")
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_class_name'

```

**Comment by lusifer021** [comment]
#158 
This PR will solve this issue

**Comment by lusifer021** [comment]
> #158 This PR will solve this issue



> ```
> selenium==4.8.3
> linkedin-scraper==2.11.0
> ```
> 
> ```
> from linkedin_scraper import Person, actions
> from selenium import webdriver
> driver = webdriver.Chrome()
> 
> email = <EMAIL>
> password = <PASSWORD>
> 
> actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
> person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5", driver=driver)
> 
> print(person.name)
> ```
> 
> =>
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/evo850/workspace/SalesBrain.tech/scripts/get_person.py", line 9, in <module>
>     person = Person("https://www.linkedin.com/in/andre-iguodala-65b48ab5", driver=driver)
>   File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 63, in __init__
>     self.scrape(close_on_complete)
>   File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 88, in scrape
>     self.scrape_logged_in(close_on_complete=close_on_complete)
>   File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 261, in scrape_logged_in
>     self.get_name_and_location()
>   File "/home/vladimir/anaconda3/envs/salesbrain.tech/lib/python3.10/site-packages/linkedin_scraper/person.py", line 235, in get_name_and_location
>     top_panels = self.driver.find_elements_by_class_name("pv-text-details__left-panel")
> AttributeError: 'WebDriver' object has no attribute 'find_elements_by_class_name'
> ```


#158 
this PR will solve this issue @ternaus

**Comment by ternaus** [comment]
@lusifer021 Let's merge it? :)

**Comment by lusifer021** [comment]
Yes, but I don't have access.

**Comment by mattsunsjf** [comment]
Also have this issue.

**Comment by javaCR7** [comment]
How to solve it?

**Comment by lusifer021** [comment]
use this PR #158 
@javaCR7 @mattsunsjf
