### ISSUE TITLE
Failing to run 

### ISSUE THREAD

**Issue by swissbeats93** [joeyism/linkedin_scraper#16]
For the life of me, I cannot get the scraper to run for a Person, may I please get the watered down version of the instructions if it's not too much to ask

**Comment by swissbeats93** [comment]
I've figured out the first part at long last. New problem now
![screen shot 2018-07-27 at 08 01 20](https://user-images.githubusercontent.com/30832909/43304330-f53e7ecc-9173-11e8-9429-ff2f0c0219cc.png)

**Comment by swissbeats93** [comment]
Tried something else and this is what I get:

Traceback (most recent call last):
  File "Execute.py", line 17, in <module>
    person = Person(linkedin_url, driver = driver, scrape = False)
  File "/Users/swissbeats93/Documents/WORK/SHC DATA ANALYSIS PROJECT/LI Scraper by PM/User.py", line 18, in __init__
    driver.get(linkedin_url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 326, in get
    self.execute(Command.GET, {'url': url})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 312, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/remote_connection.py", line 472, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-3.12.0-py3.6.egg/selenium/webdriver/remote/remote_connection.py", line 496, in _request
    resp = self._conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
