### ISSUE TITLE
Profile scraping not working

### ISSUE THREAD

**Issue by kumashankar-mbai** [joeyism/linkedin_scraper#208]
C:\Users\User\PycharmProjects\Azure_Auto_login\venv\Scripts\python.exe "C:/Program Files/JetBrains/PyCharm Community Edition 2023.1.3/plugins/python-ce/helpers/pydev/pydevconsole.py" --mode=client --host=127.0.0.1 --port=54582 
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\User\\PycharmProjects\\Azure_Auto_login'])
PyDev console: starting.
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
runfile('C:\\Users\\User\\PycharmProjects\\Azure_Auto_login\\linkedin_scraper_git.py', wdir='C:\\Users\\User\\PycharmProjects\\Azure_Auto_login')
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\User\PycharmProjects\Azure_Auto_login\linkedin_scraper_git.py", line 8, in <module>
    person = Person("https://www.linkedin.com/in/rushabhbmehta/", driver=driver)
  File "C:\Users\User\PycharmProjects\Azure_Auto_login\venv\lib\site-packages\linkedin_scraper\person.py", line 64, in __init__
    self.scrape(close_on_complete)
  File "C:\Users\User\PycharmProjects\Azure_Auto_login\venv\lib\site-packages\linkedin_scraper\person.py", line 89, in scrape
    self.scrape_logged_in(close_on_complete=close_on_complete)
  File "C:\Users\User\PycharmProjects\Azure_Auto_login\venv\lib\site-packages\linkedin_scraper\person.py", line 259, in scrape_logged_in
    root = WebDriverWait(driver, self.__WAIT_FOR_ELEMENT_TIMEOUT).until(
  File "C:\Users\User\PycharmProjects\Azure_Auto_login\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF7CCB32142+3514994]
	(No symbol) [0x00007FF7CC750CE2]
	(No symbol) [0x00007FF7CC5F76AA]
	(No symbol) [0x00007FF7CC641860]
	(No symbol) [0x00007FF7CC64197C]
	(No symbol) [0x00007FF7CC684EE7]
	(No symbol) [0x00007FF7CC66602F]
	(No symbol) [0x00007FF7CC6828F6]
	(No symbol) [0x00007FF7CC665D93]
	(No symbol) [0x00007FF7CC634BDC]
	(No symbol) [0x00007FF7CC635C64]
	GetHandleVerifier [0x00007FF7CCB5E16B+3695259]
	GetHandleVerifier [0x00007FF7CCBB6737+4057191]
	GetHandleVerifier [0x00007FF7CCBAE4E3+4023827]
	GetHandleVerifier [0x00007FF7CC8804F9+689705]
	(No symbol) [0x00007FF7CC75C048]
	(No symbol) [0x00007FF7CC758044]
	(No symbol) [0x00007FF7CC7581C9]
	(No symbol) [0x00007FF7CC7488C4]
	BaseThreadInitThunk [0x00007FFF13DE257D+29]
	RtlUserThreadStart [0x00007FFF13F6AA58+40]

I am getting this timeout exception

**Comment by mostafamdy** [comment]
same error with me Did you solve it?

**Comment by C-Nubela** [comment]
@mostafamdy @kumashankar-mbai 

Hey there! I work for Proxycurl, one of the sponsors for this project, and if you guys are looking for a more convenient way of scraping LinkedIn where you don't have to deal with debugging issues, [consider checking out our API](https://nubela.co/proxycurl/?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=comments), I think you'll find it valuable.

**Comment by maxixam** [comment]
it is looking for an element but can't find it, seems the tool stops working until it is updated with the change from linkedin.

**Comment by mostafamdy** [comment]
you can check pull requests I found the solution there 
https://github.com/joeyism/linkedin_scraper/pulls

**Comment by sach-12** [comment]
#209

**Comment by turk** [comment]
Hey @kumashankar-mbai 
if you are considering using a paid solution, I suggest you have a look at our API. https://rapidapi.com/rockapis-rockapis-default/api/linkedin-api8

**Comment by JackBlair87** [comment]
https://medium.com/@jackblair87/writing-a-live-follower-count-python-program-for-my-website-5e34631582d3

**Comment by wisdomcsharp** [comment]
You can easily scrape thousands of profiles, using services [linkedin outreach services like Linkedly AI](https://linkedly.ai)

Then connecting your flows with a webhook to services like zapier.. 

Works smoothly for me
