### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by jdtibochab** [joeyism/linkedin_scraper#232]
Times out waiting for an element to load (see below). This happens with Person() waiting for "username", and job_search.search() waiting for "jobs-search-results-list". I am not sure why because if I comment on the wait in Person(), everything works fine.

`---------------------------------------------------------------------------
TimeoutException                          Traceback (most recent call last)
Cell In[7], line 3
      1 from linkedin_scraper import JobSearch
      2 job_search = JobSearch(driver=driver, close_on_complete=False, scrape=False)
----> 3 job_listings = job_search.search("Machine Learning Engineer") # returns the list of `Job` from the first page

File ~/other/jobs/linkedin_scraper/linkedin_scraper/job_search.py:73, in JobSearch.search(self, search_term)
     70 sleep(self.WAIT_FOR_ELEMENT_TIMEOUT)
     72 job_listing_class_name = "jobs-search-results-list"
---> 73 job_listing = self.wait_for_element_to_load(name=job_listing_class_name)
     74 self.wait(10)
     76 self.scroll_class_name_element_to_page_percent(job_listing_class_name, 0.3)

File ~/other/jobs/linkedin_scraper/linkedin_scraper/objects.py:82, in Scraper.wait_for_element_to_load(self, by, name, base)
     80 def wait_for_element_to_load(self, by=By.CLASS_NAME, name="pv-top-card", base=None):
     81     base = base or self.driver
---> 82     return WebDriverWait(base, self.WAIT_FOR_ELEMENT_TIMEOUT).until(
     83         EC.presence_of_element_located(
     84             (
     85                 by,
     86                 name
     87             )
     88         )
     89     )

File ~/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105, in WebDriverWait.until(self, method, message)
    103         break
    104     time.sleep(self._poll)
--> 105 raise TimeoutException(message, screen, stacktrace)

TimeoutException: Message: 
Stacktrace:
#0 0x571003f45c5a <unknown>
#1 0x571003c28e2c <unknown>
#2 0x571003c75661 <unknown>
#3 0x571003c75751 <unknown>
#4 0x571003cb9f64 <unknown>
#5 0x571003c985ed <unknown>
#6 0x571003cb7303 <unknown>
#7 0x571003c98363 <unknown>
#8 0x571003c68247 <unknown>
#9 0x571003c68b9e <unknown>
#10 0x571003f0c22b <unknown>
#11 0x571003f102d1 <unknown>
#12 0x571003ef7ade <unknown>
#13 0x571003f10e32 <unknown>
#14 0x571003edc77f <unknown>
#15 0x571003f35618 <unknown>
#16 0x571003f357f0 <unknown>
#17 0x571003f44d8c <unknown>
#18 0x7f90bb494ac3 <unknown>
`

**Comment by Melchizedek13** [comment]
@jdtibochab , thanks for opening this issue!

The same problem.

```python
import os
from pprint import pprint as pp

from linkedin_scraper import actions, Company
from selenium import webdriver

driver = webdriver.Chrome()

def get_linkedin_campaign_info(linkedin_company_url: str = "https://www.linkedin.com/company/oxagile/"):
    linkedin_email = os.environ['LINKEDIN_EMAIL']
    linkedin_password = os.environ['LINKEDIN_PASSWORD']
    actions.login(driver, linkedin_email, linkedin_password)

    return Company(linkedin_company_url, driver=driver)

if __name__ == '__main__':
    pp(
        get_linkedin_campaign_info("https://ca.linkedin.com/company/google")
    )
```

```log
Traceback (most recent call last):
  File "/Users/nikolaysokolov/git/oxagile/gbs-repo/linkedin_compain_crawler.py", line 22, in <module>
    get_linkedin_campaign_info("https://ca.linkedin.com/company/google")
  File "/Users/nikolaysokolov/git/oxagile/gbs-repo/linkedin_compain_crawler.py", line 18, in get_linkedin_campaign_info
    return Company(linkedin_company_url, driver=driver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolaysokolov/.pyenv/versions/oxa_gbs_3.12/lib/python3.12/site-packages/linkedin_scraper/company.py", line 80, in __init__
    self.scrape(get_employees=get_employees, close_on_complete=close_on_complete)
  File "/Users/nikolaysokolov/.pyenv/versions/oxa_gbs_3.12/lib/python3.12/site-packages/linkedin_scraper/company.py", line 90, in scrape
    self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
  File "/Users/nikolaysokolov/.pyenv/versions/oxa_gbs_3.12/lib/python3.12/site-packages/linkedin_scraper/company.py", line 283, in scrape_logged_in
    self.employees = self.get_employees()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolaysokolov/.pyenv/versions/oxa_gbs_3.12/lib/python3.12/site-packages/linkedin_scraper/company.py", line 131, in get_employees
    _ = WebDriverWait(driver, 3).until(EC.presence_of_all_elements_located((By.XPATH, '//span[@dir="ltr"]')))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolaysokolov/.pyenv/versions/oxa_gbs_3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by kurokirasama** [comment]
i'm getting the same message

**Comment by zigpot** [comment]
@jdtibochab please check the new PR [#234](https://github.com/joeyism/linkedin_scraper/pull/234) and let me know.

**Comment by jdtibochab** [comment]
Thanks! PR-234 fixes Person, but I am still facing an error when calling JobSearch. It waits for "jobs-search-results-list" and times out. It might be a different issue, maybe from my side somehow, will look into it.

**Comment by zigpot** [comment]
> Thanks! PR-234 fixes Person, but I am still facing the same error above when calling JobSearch. It waits for "jobs-search-results-list" and times out. It might be a different issue, maybe from my side somehow, will look into it.

my bad, it was job, not job search. will look into it in a jiffy!

**Comment by vuquocan1987** [comment]
Hi, is there update on this?
