### ISSUE TITLE
Running on Company page fails

### ISSUE THREAD

**Issue by greggmojica** [joeyism/linkedin_scraper#24]
When running on a company page (i.e. Google example) I'm getting this error. How can this be resolved?

```
Traceback (most recent call last):

  File "scrape_person.py", line 11, in <module>
    company = Company("https://linkedin.com/company/first-data-corporation", driver=driver)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/linkedin_scraper/company.py", line 69, in __init__
    self.scrape(get_employees=get_employees, close_on_complete=close_on_complete)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/linkedin_scraper/company.py", line 79, in scrape
    self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/linkedin_scraper/company.py", line 140, in scrape_logged_in
    _ = WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.XPATH, '//h1[@dir="ltr"]')))
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

```

**Comment by joeyism** [comment]
Just published `2.4.1`, which should fix this issue
