### ISSUE TITLE
IndexError when scraping certain companies

### ISSUE THREAD

**Issue by neil-design** [joeyism/linkedin_scraper#33]
Forgive me if this is an error on my part, but for most company urls, when I try to scrape I get an IndexError for various lines under scrape_logged_in (also reloads each company page 2-3 times). Sample code and error below (first company works, second doesn't):

`Traceback (most recent call last):
  File "LItest.py", line 16, in <module>
    company = Company("https://www.linkedin.com/company/archimedes-rx/about", driver=driver, get_employees=False, close_on_complete=False)
  File "C:\Users\n****\AppData\Local\Programs\Python\Python37\lib\site-packages\linkedin_scraper\company.py", line 69, in __init__
    self.scrape(get_employees=get_employees, close_on_complete=close_on_complete)
  File "C:\Users\n****\AppData\Local\Programs\Python\Python37\lib\site-packages\linkedin_scraper\company.py", line 79, in scrape
    self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
  File "C:\Users\n****\AppData\Local\Programs\Python\Python37\lib\site-packages\linkedin_scraper\company.py", line 156, in scrape_logged_in
    self.specialties = "\n".join(values[-1].text.strip().split(", "))
IndexError: list index out of range`

```
from linkedin_scraper import Company, actions
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())
email = "MYEMAIL"
password = "MYPASSWORD"
actions.login(driver, email, password)
company = Company("https://www.linkedin.com/company/archimedes-rx", driver=driver, get_employees=False, close_on_complete=False)
companytwo = Company("https://www.linkedin.com/company/life360", driver=driver, get_employees=False)
print(companytwo)
```

**Comment by joeyism** [comment]
This is what I get
```
   ...: actions.login(driver, email, password)
   ...: company = Company("https://www.linkedin.com/company/archimedes-rx", driver=driver, get_employees=False, close_on_complete=False)
   ...: companytwo = Company("https://www.linkedin.com/company/life360", driver=driver, get_employees=False)
   ...: print(companytwo)

Life360

Life360 is a platform for today’s busy families, bringing them closer together by helping to protect and connect the people they care about most.  Our service provides millions of families in over 140 countries with features such as location sharing, private messaging, driver monitoring, car crash detection, and help alerts through our free and paid membership offerings.

We are growing rapidly, and have been a Top 50 app for over 3 years in a row, making us the largest mobile service for families in the world. Our customer base exceeds 25 million active users, who on average use the service over 10 times a day. We monetize primarily through subscription services, and are approaching $100m in annualized revenue. Our team is also on the forefront of a broad range of technologies (mobile, location services, hardware sensors, machine learning, big data) and maintains an infrastructure that handles billions of location points a day and collects over 20 billion miles a month of driving data (more than Uber or Lyft).

Life360 has raised over $200 million in equity financing, and recently completed an IPO on the ASX exchange, which gives our employees the liquidity of a public company with the upside of a private growth stage business. The team consists of 150+ employees, with offices in San Francisco, San Diego, and Las Vegas.

Life360 is a high-growth, freemium consumer mobile company that has raised >$200 million in equity capital since inception.  Our customer base, which currently exceeds 25 million monthly active users (MAU), has enabled us to become one of the world's largest sources of consumer driving data with more than 23 billion miles collected per month as of Sept 2019.  The company is at the forefront of a broad range of technologies (mobile, location services, hardware sensors, machine learning, big data, etc) in pioneering its family-centric platform.

Specialties: Family Networking
Location Based Services
Mobile
Connected Home
Connected Car
and consumer tech

Website: http://www.life360.com
Industry: 51-200 employees
Type: None
Headquarters: Public Company
Company Size: 169 on LinkedIn
Includes members with current employer listed as Life360, including part-time roles.
Founded: None

Showcase Pages
[]

Affiliated Companies
[]

```

**Comment by adityaketkar** [comment]
Hi. I am able to reproduce the same error. Here is the error : 
```
 IndexError                                Traceback (most recent call last)
<ipython-input-23-d905020a2f53> in <module>
      6 password = "asdfgh69"
      7 actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
----> 8 person = Company("https://www.linkedin.com/company/qubole/", driver=driver)

~/anaconda3/envs/minerva/lib/python3.7/site-packages/linkedin_scraper/company.py in __init__(self, linkedin_url, name, about_us, website, headquarters, founded, company_type, company_size, specialties, showcase_pages, affiliated_companies, driver, scrape, get_employees, close_on_complete)
     67 
     68         if scrape:
---> 69             self.scrape(get_employees=get_employees, close_on_complete=close_on_complete)
     70 
     71     def __get_text_under_subtitle(self, elem):

~/anaconda3/envs/minerva/lib/python3.7/site-packages/linkedin_scraper/company.py in scrape(self, get_employees, close_on_complete)
     77     def scrape(self, get_employees = True, close_on_complete = True):
     78         if self.is_signed_in():
---> 79             self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
     80         else:
     81             self.scrape_not_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)

~/anaconda3/envs/minerva/lib/python3.7/site-packages/linkedin_scraper/company.py in scrape_logged_in(self, get_employees, close_on_complete)
    154 
    155         values = grid.find_elements_by_tag_name("dd")
--> 156         self.specialties = "\n".join(values[-1].text.strip().split(", "))
    157         self.website = values[0].text.strip()
    158         self.headquarters = values[5].text.strip()

IndexError: list index out of range 
```

Here is the code I ran : 
```
from linkedin_scraper import Person, actions, Company
from selenium import webdriver
driver = webdriver.Chrome()

email = "EMAIL"
password = "PASSWORD"
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Company("https://www.linkedin.com/company/qubole/", driver=driver
)```

I am using the latest version. Any ideas why this might be happening?

**Comment by adityaketkar** [comment]
Hi. I am able to reproduce the same error. Here is the error : 
```
 IndexError                                Traceback (most recent call last)
<ipython-input-23-d905020a2f53> in <module>
      6 password = "PASSWORD"
      7 actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
----> 8 person = Company("https://www.linkedin.com/company/qubole/", driver=driver)

~/anaconda3/envs/minerva/lib/python3.7/site-packages/linkedin_scraper/company.py in __init__(self, linkedin_url, name, about_us, website, headquarters, founded, company_type, company_size, specialties, showcase_pages, affiliated_companies, driver, scrape, get_employees, close_on_complete)
     67 
     68         if scrape:
---> 69             self.scrape(get_employees=get_employees, close_on_complete=close_on_complete)
     70 
     71     def __get_text_under_subtitle(self, elem):

~/anaconda3/envs/minerva/lib/python3.7/site-packages/linkedin_scraper/company.py in scrape(self, get_employees, close_on_complete)
     77     def scrape(self, get_employees = True, close_on_complete = True):
     78         if self.is_signed_in():
---> 79             self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
     80         else:
     81             self.scrape_not_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)

~/anaconda3/envs/minerva/lib/python3.7/site-packages/linkedin_scraper/company.py in scrape_logged_in(self, get_employees, close_on_complete)
    154 
    155         values = grid.find_elements_by_tag_name("dd")
--> 156         self.specialties = "\n".join(values[-1].text.strip().split(", "))
    157         self.website = values[0].text.strip()
    158         self.headquarters = values[5].text.strip()

IndexError: list index out of range 
```

Here is the code I ran : 
```
from linkedin_scraper import Person, actions, Company
from selenium import webdriver
driver = webdriver.Chrome()

email = "EMAIL"
password = "PASSWORD"
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Company("https://www.linkedin.com/company/qubole/", driver=driver
)
```

I am using the latest version. Any ideas why this might be happening?

**Comment by joeyism** [comment]
Can you tell me the resolution of your window? I find this only happens when I have low window width. To solve that with headless Chrome, you can run

```python
import os
from linkedin_scraper import Person, actions, Company
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
chrome_options.add_argument("--headless")
driver = webdriver.Chrome("./chromedriver", options=chrome_options)
driver.set_window_size(1920, 1080)


email = os.getenv("LINKEDIN_USER")
password = os.getenv("LINKEDIN_PASSWORD")
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Company("https://www.linkedin.com/company/qubole/", driver=driver)
```
