### ISSUE TITLE
Company Scrapping not working.

### ISSUE THREAD

**Issue by laksh9950** [joeyism/linkedin_scraper#49]
**Traceback (most recent call last):
  File "C:\Users\LAksh\Desktop\test.py", line 14, in <module>
    person = Company("https://www.linkedin.com/company/qubole/", driver=driver)
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\linkedin_scraper\company.py", line 69, in __init__
    self.scrape(get_employees=get_employees, close_on_complete=close_on_complete)
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\linkedin_scraper\company.py", line 79, in scrape
    self.scrape_logged_in(get_employees = get_employees, close_on_complete = close_on_complete)
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\linkedin_scraper\company.py", line 194, in scrape_logged_in
    self.employees = self.get_employees()
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\linkedin_scraper\company.py", line 131, in get_employees
    _ = WebDriverWait(driver, wait_time).until(EC.visibility_of(res))
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 144, in __call__
    return _element_if_visible(self.element)
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 148, in _element_if_visible
    return element if element.is_displayed() == visibility else False
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 488, in is_displayed
    self)
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\LAksh\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=83.0.4103.116)

**

Error details 
code 
``` python
import os
from linkedin_scraper import Person, actions, Company
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
chrome_options.add_argument("--headless")
driver = webdriver.Chrome("C:\\Users\\LAksh\\Downloads\\chromedriver_win32\\chromedriver", options=chrome_options)
driver.set_window_size(1920, 1080)


email = ""
password = ""
actions.login(driver, email, password) # if email and password isnt given, it'll prompt in terminal
person = Company("https://www.linkedin.com/company/qubole/", driver=driver)
print(person)
```

**Comment by joeyism** [comment]
You have to add in your own email and password to `email` and `password` (if you're worried about security, you can save as an environment variable or have it prompt you without passing anything in).

After that, your result should be
```
Qubole

Qubole delivers a Self-Service Platform for Big Data Analytics built on Amazon Web Services, Microsoft and Google Clouds.

We were started by the team that built and ran Facebook's Data Service when they founded and authored Apache Hive.  With Qubole, a data scientist can now spin up hundreds of clusters on their public cloud of choice and begin creating ad hoc and/or batch queries in under five minutes and have the system autoscale to the optimal compute levels as needed.  Please feel free to test Qubole Data Services for yourself by clicking "Free Trial" on the website.

Specialties: Public cloud-based data analytics
Hive
Spark
Presto
Pig
SQL
Big Data as a Service
AWS
Azure
Machine Learning
ETL
DataLake Analytics
and Big Data Platform

Website: http://www.qubole.com
Industry: 201-500 employees
Type: None
Headquarters: Privately Held
Company Size: 339 on LinkedIn
Includes members with current employer listed as Qubole, including part-time roles.
Founded: None

Showcase Pages
[]

Affiliated Companies
[]
```
